#!/usr/bin/env python3
import os, glob

src_files = set(glob.glob('src/**/*.ts', recursive=True))

for file in src_files:
    os.system(f'tsc {file}')

compiled_src_files = set(glob.glob('src/**/*.js', recursive=True))

os.system('rm ./float/src/')
os.system('mv ')